spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: 192.168.33.128:9200
          connection-timeout: 10000
          socket-timeout: 10000
  elasticsearch:
    rest:
      uris: 192.168.33.128:9200